spring:
  application:
    name: examQuestionBank

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # tblog 데이터베이스가 실제로 생성되어 있는지 확인하세요!
    url: jdbc:mysql://localhost:3306/tblog?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: '1234' # 숫자로만 된 비밀번호는 따옴표로 감싸는 것이 안전합니다.

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: true #바로 적용됨
    locations: classpath:db/migration
    baseline-on-migrate: false # 이미스키마 존재하는 상태에서 할거임?
    validate-on-migrate: true # Migration 파일 무결성 체크
